// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBGGnJVMwASSPMTaZ2yG0tJy3UahMv-c8',
    appId: '1:1029070544602:web:32a1a0f3e834fd2c3b8fe3',
    messagingSenderId: '1029070544602',
    projectId: 'portfolio-kunalmanocha',
    authDomain: 'portfolio-kunalmanocha.firebaseapp.com',
    storageBucket: 'portfolio-kunalmanocha.appspot.com',
    measurementId: 'G-7V0D8D8MJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH_Nyq5d0a3cIW0W-DRqXq3TNhdoX0TLs',
    appId: '1:1029070544602:android:0e50a3578e4d42af3b8fe3',
    messagingSenderId: '1029070544602',
    projectId: 'portfolio-kunalmanocha',
    storageBucket: 'portfolio-kunalmanocha.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzcfVkPlLTBGcb-XAkJFrxgA34j8nuWog',
    appId: '1:1029070544602:ios:05057d318388c4623b8fe3',
    messagingSenderId: '1029070544602',
    projectId: 'portfolio-kunalmanocha',
    storageBucket: 'portfolio-kunalmanocha.appspot.com',
    iosBundleId: 'com.kunalmanocha.portfolio.portfolio',
  );
}
